name: Erudio-PyTorch
channels:
  - conda-forge
  - pytorch
dependencies:
  - python=3
  - pip
  - pip:
      - torch
      - torchsummary
      - keras
      - tensorflow
      - scikit-learn
      - torchvision
      - pandas
      - numpy
      - matplotlib
      - jupyter
      - seaborn
      - pillow
      - allennlp
